# Generated by Django 5.1.4 on 2024-12-26 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agri_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='admin_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='admin',
            name='admin_phone_no',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='farmer_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='farmer_phone_no',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='gateway',
            name='gateway_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='gateway',
            name='mac_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='gateway_farmer',
            name='gateway_farmer_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='motor',
            name='mac_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='motor',
            name='motor_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='motor_farmer',
            name='motor_farmer_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='motor_operation',
            name='motor_operation_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='mac_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='sensor_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sensor_data',
            name='sensor_data_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sensor_farmer',
            name='sensor_farmer_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='valve',
            name='mac_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='valve',
            name='valve_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='valve_farmer',
            name='valve_farmer_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='valve_operation',
            name='valve_operation_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
