# Generated by Django 5.1.4 on 2024-12-27 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agri_app', '0002_alter_admin_admin_id_alter_admin_admin_phone_no_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Admin',
            new_name='Agri_admin',
        ),
    ]
