# Generated by Django 5.1.4 on 2024-12-27 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agri_app', '0003_passwordreset'),
        ('agri_app', '0003_rename_admin_agri_admin'),
    ]

    operations = [
    ]
