# Generated by Django 4.2.3 on 2024-12-30 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agri_app', '0004_merge_0003_passwordreset_0003_rename_admin_agri_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agri_admin',
            name='extra_field1',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='agri_admin',
            name='extra_field2',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='agri_admin',
            name='extra_field3',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='extra_field1',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='extra_field2',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='extra_field3',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='gateway',
            name='extra_field1',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='gateway',
            name='extra_field2',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='gateway',
            name='extra_field3',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='gateway_farmer',
            name='extra_field1',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='gateway_farmer',
            name='extra_field2',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='gateway_farmer',
            name='extra_field3',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='motor',
            name='extra_field1',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='motor',
            name='extra_field2',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='motor',
            name='extra_field3',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='motor_farmer',
            name='extra_field1',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='motor_farmer',
            name='extra_field2',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='motor_farmer',
            name='extra_field3',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='motor_operation',
            name='extra_field1',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='motor_operation',
            name='extra_field2',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='motor_operation',
            name='extra_field3',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='extra_field1',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='extra_field2',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='extra_field3',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sensor_data',
            name='extra_field1',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sensor_data',
            name='extra_field2',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sensor_data',
            name='extra_field3',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sensor_farmer',
            name='extra_field1',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sensor_farmer',
            name='extra_field2',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sensor_farmer',
            name='extra_field3',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='valve',
            name='extra_field1',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='valve',
            name='extra_field2',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='valve',
            name='extra_field3',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='valve_farmer',
            name='extra_field1',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='valve_farmer',
            name='extra_field2',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='valve_farmer',
            name='extra_field3',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='valve_operation',
            name='extra_field1',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='valve_operation',
            name='extra_field2',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='valve_operation',
            name='extra_field3',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
